# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_path = QtWidgets.QLineEdit(self.centralwidget)
        self.text_path.setGeometry(QtCore.QRect(60, 280, 400, 30))
        self.text_path.setText("")
        self.text_path.setObjectName("text_path")
        self.button_path_text = QtWidgets.QPushButton(self.centralwidget)
        self.button_path_text.setGeometry(QtCore.QRect(630, 280, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_path_text.setFont(font)
        self.button_path_text.setObjectName("button_path_text")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 800, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.button_new_window = QtWidgets.QPushButton(self.centralwidget)
        self.button_new_window.setGeometry(QtCore.QRect(680, 540, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_new_window.setFont(font)
        self.button_new_window.setObjectName("button_new_window")
        self.label_text_description = QtWidgets.QLabel(self.centralwidget)
        self.label_text_description.setGeometry(QtCore.QRect(60, 210, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_description.setFont(font)
        self.label_text_description.setObjectName("label_text_description")
        self.label_audio_description = QtWidgets.QLabel(self.centralwidget)
        self.label_audio_description.setGeometry(QtCore.QRect(60, 360, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_audio_description.setFont(font)
        self.label_audio_description.setObjectName("label_audio_description")
        self.button_path_audio = QtWidgets.QPushButton(self.centralwidget)
        self.button_path_audio.setGeometry(QtCore.QRect(630, 400, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_path_audio.setFont(font)
        self.button_path_audio.setObjectName("button_path_audio")
        self.audio_path = QtWidgets.QLineEdit(self.centralwidget)
        self.audio_path.setGeometry(QtCore.QRect(60, 400, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.audio_path.setFont(font)
        self.audio_path.setObjectName("audio_path")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button_path_text.clicked.connect(self.get_text_path)
        self.button_path_audio.clicked.connect(self.get_audio_path)
        self.button_new_window.clicked.connect(self.new_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_path_text.setText(_translate("MainWindow", "Scegli file"))
        self.label_title.setText(_translate("MainWindow", "WELCOME TO VIDEOMAKER"))
        self.button_new_window.setText(_translate("MainWindow", "Avanti"))
        self.label_text_description.setText(_translate("MainWindow", "Choose a text file"))
        self.label_audio_description.setText(_translate("MainWindow", "Choose a audio file, must be .wav"))
        self.button_path_audio.setText(_translate("MainWindow", "Scegli file"))

    def get_text_path(self):
        text_file_name, _ = QtWidgets.QFileDialog.getOpenFileName(caption="Choose a text file", filter="Text files (*.txt)")
        self.text_path.setText(text_file_name)

    def get_audio_path(self):
        audio_file_name, _ = QtWidgets.QFileDialog.getOpenFileName(caption="Choose an audio file", filter="Audio files (*.wav)")
        self.audio_path.setText(audio_file_name)
    
    def new_window(self):
        # self.downloaderWindow = QtWidgets.QMa()
        # self.ui = Ui_DownloaderWindow()
        # self.ui.setupUi(self.downloaderWindow)
        # self.setupUi(self.downloaderWindow)
        if self.text_path.text() and self.audio_path.text():
            pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
