# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\downloaderUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from downloader import ImageDownloader

class Ui_DownloaderWindow(object):
    
    def __init__(self, file_text_path):
        self.file_text_path = file_text_path
    
    def setupUi(self, DownloaderWindow):
        DownloaderWindow.setObjectName("DownloaderWindow")
        DownloaderWindow.resize(800, 600)
        self.label_title = QtWidgets.QLabel(DownloaderWindow)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 800, 40))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_description = QtWidgets.QLabel(DownloaderWindow)
        self.label_description.setGeometry(QtCore.QRect(0, 40, 800, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_description.setFont(font)
        self.label_description.setObjectName("label_description")
        self.label_info = QtWidgets.QLabel(DownloaderWindow)
        self.label_info.setGeometry(QtCore.QRect(0, 65, 800, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_info.setFont(font)
        self.label_info.setObjectName("label_info")
        self.button_back = QtWidgets.QPushButton(DownloaderWindow)
        self.button_back.setGeometry(QtCore.QRect(20, 540, 100, 40))
        self.button_back.setObjectName("button_back")
        self.label_image = QtWidgets.QLabel(DownloaderWindow)
        self.label_image.setGeometry(QtCore.QRect(100, 100, 600, 430))
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.button_next_image = QtWidgets.QPushButton(DownloaderWindow)
        self.button_next_image.setGeometry(QtCore.QRect(720, 285, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_next_image.setFont(font)
        self.button_next_image.setObjectName("button_next_image")
        self.button_back_image = QtWidgets.QPushButton(DownloaderWindow)
        self.button_back_image.setGeometry(QtCore.QRect(20, 285, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_back_image.setFont(font)
        self.button_back_image.setObjectName("button_back_image")
        self.button_select_image = QtWidgets.QPushButton(DownloaderWindow)
        self.button_select_image.setGeometry(QtCore.QRect(720, 325, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_select_image.setFont(font)
        self.button_select_image.setObjectName("button_select_image")
        self.button_create_video = QtWidgets.QPushButton(DownloaderWindow)
        self.button_create_video.setGeometry(QtCore.QRect(700, 560, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_create_video.setFont(font)
        self.button_create_video.setObjectName("button_create_video")
        
        self.retranslateUi(DownloaderWindow)
        QtCore.QMetaObject.connectSlotsByName(DownloaderWindow)

        #my edit to QTdesigner code
        self.image_downloader = ImageDownloader(self.file_text_path)

    def retranslateUi(self, DownloaderWindow):
        _translate = QtCore.QCoreApplication.translate
        DownloaderWindow.setWindowTitle(_translate("DownloaderWindow", "Image Downloader"))
        self.label_title.setText(_translate("DownloaderWindow", "Downloader"))
        self.label_description.setText(_translate("DownloaderWindow", "Downloading..."))
        self.label_info.setText(_translate("DownloaderWindow", "Choose an image to donwload for "))
        self.button_back.setText(_translate("DownloaderWindow", "Indietro"))
        self.button_next_image.setText(_translate("DownloaderWindow", "Next"))
        self.button_back_image.setText(_translate("DownloaderWindow", "Back"))
        self.button_select_image.setText(_translate("DownloaderWindow", "Select"))
        self.button_create_video.setText(_translate("DownloaderWindow", "Create Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DownloaderWindow = QtWidgets.QWidget()
    ui = Ui_DownloaderWindow()
    ui.setupUi(DownloaderWindow)
    DownloaderWindow.show()
    sys.exit(app.exec_())
