# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.label_title = QtWidgets.QLabel(mainWindow)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 800, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_text_description = QtWidgets.QLabel(mainWindow)
        self.label_text_description.setGeometry(QtCore.QRect(60, 210, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_description.setFont(font)
        self.label_text_description.setObjectName("label_text_description")
        self.text_path = QtWidgets.QLineEdit(mainWindow)
        self.text_path.setGeometry(QtCore.QRect(60, 280, 400, 30))
        self.text_path.setText("")
        self.text_path.setObjectName("text_path")
        self.audio_path = QtWidgets.QLineEdit(mainWindow)
        self.audio_path.setGeometry(QtCore.QRect(60, 400, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.audio_path.setFont(font)
        self.audio_path.setObjectName("audio_path")
        self.label_audio_description = QtWidgets.QLabel(mainWindow)
        self.label_audio_description.setGeometry(QtCore.QRect(60, 360, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_audio_description.setFont(font)
        self.label_audio_description.setObjectName("label_audio_description")
        self.button_path_text = QtWidgets.QPushButton(mainWindow)
        self.button_path_text.setGeometry(QtCore.QRect(630, 280, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_path_text.setFont(font)
        self.button_path_text.setObjectName("button_path_text")
        self.button_path_audio = QtWidgets.QPushButton(mainWindow)
        self.button_path_audio.setGeometry(QtCore.QRect(630, 400, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_path_audio.setFont(font)
        self.button_path_audio.setObjectName("button_path_audio")
        self.button_new_window = QtWidgets.QPushButton(mainWindow)
        self.button_new_window.setGeometry(QtCore.QRect(680, 540, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_new_window.setFont(font)
        self.button_new_window.setObjectName("button_new_window")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

        self.button_path_text.clicked.connect(self.setTextPath)
        self.button_path_audio.clicked.connect(self.setAudioPath)

    def getPaths(self):
        return [self.text_path.text(), self.audio_path.text()]

    def setTextPath(self):
        fname, _ = QtWidgets.QFileDialog.getOpenFileName( caption="Choose a text file", filter="Text file (*.txt)")
        self.text_path.setText(fname)
    
    def setAudioPath(self):
        fname, _ = QtWidgets.QFileDialog.getOpenFileName( caption="Choose an audio file", filter="Text file (*.wav)")
        self.audio_path.setText(fname)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "File Selector"))
        self.label_title.setText(_translate("mainWindow", "WELCOME TO VIDEOMAKER"))
        self.label_text_description.setText(_translate("mainWindow", "Choose a text file"))
        self.label_audio_description.setText(_translate("mainWindow", "Choose a audio file, must be .wav"))
        self.button_path_text.setText(_translate("mainWindow", "Scegli File"))
        self.button_path_audio.setText(_translate("mainWindow", "PushButton"))
        self.button_new_window.setText(_translate("mainWindow", "Avanti"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QWidget()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
